# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\" \n\x0ePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\"\"\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x45\n\x0ePaymentService\x12\x33\n\x0eProcessPayment\x12\x0f.PaymentRequest\x1a\x10.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=17
  _globals['_PAYMENTREQUEST']._serialized_end=49
  _globals['_PAYMENTRESPONSE']._serialized_start=51
  _globals['_PAYMENTRESPONSE']._serialized_end=85
  _globals['_PAYMENTSERVICE']._serialized_start=87
  _globals['_PAYMENTSERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
