# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import deneme_pb2 as deneme__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in deneme_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class servisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.bolme = channel.unary_unary(
                '/greet.servis/bolme',
                request_serializer=deneme__pb2.istek_sayilar.SerializeToString,
                response_deserializer=deneme__pb2.cevap_bolme.FromString,
                _registered_method=True)
        self.selamla = channel.unary_unary(
                '/greet.servis/selamla',
                request_serializer=deneme__pb2.istek_isim.SerializeToString,
                response_deserializer=deneme__pb2.cevap_selamla.FromString,
                _registered_method=True)


class servisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def bolme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def selamla(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_servisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'bolme': grpc.unary_unary_rpc_method_handler(
                    servicer.bolme,
                    request_deserializer=deneme__pb2.istek_sayilar.FromString,
                    response_serializer=deneme__pb2.cevap_bolme.SerializeToString,
            ),
            'selamla': grpc.unary_unary_rpc_method_handler(
                    servicer.selamla,
                    request_deserializer=deneme__pb2.istek_isim.FromString,
                    response_serializer=deneme__pb2.cevap_selamla.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.servis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greet.servis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class servis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def bolme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.servis/bolme',
            deneme__pb2.istek_sayilar.SerializeToString,
            deneme__pb2.cevap_bolme.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def selamla(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.servis/selamla',
            deneme__pb2.istek_isim.SerializeToString,
            deneme__pb2.cevap_selamla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
