# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deneme.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'deneme.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65neme.proto\x12\x05greet\"/\n\ristek_sayilar\x12\x0e\n\x06sayi_1\x18\x01 \x01(\x05\x12\x0e\n\x06sayi_2\x18\x02 \x01(\x05\"\x1a\n\nistek_isim\x12\x0c\n\x04isim\x18\x01 \x01(\t\"+\n\x0b\x63\x65vap_bolme\x12\r\n\x05\x62olum\x18\x01 \x01(\x05\x12\r\n\x05kalan\x18\x02 \x01(\x05\"\x1e\n\rcevap_selamla\x12\r\n\x05mesaj\x18\x01 \x01(\t2s\n\x06servis\x12\x33\n\x05\x62olme\x12\x14.greet.istek_sayilar\x1a\x12.greet.cevap_bolme\"\x00\x12\x34\n\x07selamla\x12\x11.greet.istek_isim\x1a\x14.greet.cevap_selamla\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deneme_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISTEK_SAYILAR']._serialized_start=23
  _globals['_ISTEK_SAYILAR']._serialized_end=70
  _globals['_ISTEK_ISIM']._serialized_start=72
  _globals['_ISTEK_ISIM']._serialized_end=98
  _globals['_CEVAP_BOLME']._serialized_start=100
  _globals['_CEVAP_BOLME']._serialized_end=143
  _globals['_CEVAP_SELAMLA']._serialized_start=145
  _globals['_CEVAP_SELAMLA']._serialized_end=175
  _globals['_SERVIS']._serialized_start=177
  _globals['_SERVIS']._serialized_end=292
# @@protoc_insertion_point(module_scope)
