# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x05greet\"-\n\nistek_sayi\x12\x0f\n\x07\x62irinci\x18\x01 \x01(\x05\x12\x0e\n\x06ikinci\x18\x02 \x01(\x05\"\x1e\n\x0c\x63\x65vap_toplam\x12\x0e\n\x06toplam\x18\x01 \x01(\x05\"\x1a\n\nistek_isim\x12\x0c\n\x04isim\x18\x01 \x01(\t\" \n\x0f\x63\x65vap_selamlama\x12\r\n\x05mesaj\x18\x01 \x01(\t2t\n\x05Yusuf\x12\x33\n\x07toplama\x12\x11.greet.istek_sayi\x1a\x13.greet.cevap_toplam\"\x00\x12\x36\n\x07selamla\x12\x11.greet.istek_isim\x1a\x16.greet.cevap_selamlama\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISTEK_SAYI']._serialized_start=21
  _globals['_ISTEK_SAYI']._serialized_end=66
  _globals['_CEVAP_TOPLAM']._serialized_start=68
  _globals['_CEVAP_TOPLAM']._serialized_end=98
  _globals['_ISTEK_ISIM']._serialized_start=100
  _globals['_ISTEK_ISIM']._serialized_end=126
  _globals['_CEVAP_SELAMLAMA']._serialized_start=128
  _globals['_CEVAP_SELAMLAMA']._serialized_end=160
  _globals['_YUSUF']._serialized_start=162
  _globals['_YUSUF']._serialized_end=278
# @@protoc_insertion_point(module_scope)
