# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YusufStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.toplama = channel.unary_unary(
                '/greet.Yusuf/toplama',
                request_serializer=grpc__pb2.istek_sayi.SerializeToString,
                response_deserializer=grpc__pb2.cevap_toplam.FromString,
                _registered_method=True)
        self.selamla = channel.unary_unary(
                '/greet.Yusuf/selamla',
                request_serializer=grpc__pb2.istek_isim.SerializeToString,
                response_deserializer=grpc__pb2.cevap_selamlama.FromString,
                _registered_method=True)


class YusufServicer(object):
    """Missing associated documentation comment in .proto file."""

    def toplama(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def selamla(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YusufServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'toplama': grpc.unary_unary_rpc_method_handler(
                    servicer.toplama,
                    request_deserializer=grpc__pb2.istek_sayi.FromString,
                    response_serializer=grpc__pb2.cevap_toplam.SerializeToString,
            ),
            'selamla': grpc.unary_unary_rpc_method_handler(
                    servicer.selamla,
                    request_deserializer=grpc__pb2.istek_isim.FromString,
                    response_serializer=grpc__pb2.cevap_selamlama.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.Yusuf', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greet.Yusuf', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Yusuf(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def toplama(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.Yusuf/toplama',
            grpc__pb2.istek_sayi.SerializeToString,
            grpc__pb2.cevap_toplam.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def selamla(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.Yusuf/selamla',
            grpc__pb2.istek_isim.SerializeToString,
            grpc__pb2.cevap_selamlama.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
