# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: last_dance.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'last_dance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10last_dance.proto\x12\x05greet\"/\n\ristek_sayilar\x12\x0e\n\x06sayi_1\x18\x01 \x01(\x05\x12\x0e\n\x06sayi_2\x18\x02 \x01(\x05\"\x1e\n\x0c\x63\x65vap_toplam\x12\x0e\n\x06toplam\x18\x01 \x01(\x05\"/\n\ristek_isimler\x12\x0e\n\x06isim_1\x18\x01 \x01(\t\x12\x0e\n\x06isim_2\x18\x02 \x01(\t\"\x1a\n\ncevap_isim\x12\x0c\n\x04isim\x18\x01 \x01(\t2~\n\nson_servis\x12\x36\n\x07toplama\x12\x14.greet.istek_sayilar\x1a\x13.greet.cevap_toplam\"\x00\x12\x38\n\x0b\x62irlestirme\x12\x14.greet.istek_isimler\x1a\x11.greet.cevap_isim\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'last_dance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISTEK_SAYILAR']._serialized_start=27
  _globals['_ISTEK_SAYILAR']._serialized_end=74
  _globals['_CEVAP_TOPLAM']._serialized_start=76
  _globals['_CEVAP_TOPLAM']._serialized_end=106
  _globals['_ISTEK_ISIMLER']._serialized_start=108
  _globals['_ISTEK_ISIMLER']._serialized_end=155
  _globals['_CEVAP_ISIM']._serialized_start=157
  _globals['_CEVAP_ISIM']._serialized_end=183
  _globals['_SON_SERVIS']._serialized_start=185
  _globals['_SON_SERVIS']._serialized_end=311
# @@protoc_insertion_point(module_scope)
