# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import last_dance_pb2 as last__dance__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in last_dance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class son_servisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.toplama = channel.unary_unary(
                '/greet.son_servis/toplama',
                request_serializer=last__dance__pb2.istek_sayilar.SerializeToString,
                response_deserializer=last__dance__pb2.cevap_toplam.FromString,
                _registered_method=True)
        self.birlestirme = channel.unary_unary(
                '/greet.son_servis/birlestirme',
                request_serializer=last__dance__pb2.istek_isimler.SerializeToString,
                response_deserializer=last__dance__pb2.cevap_isim.FromString,
                _registered_method=True)


class son_servisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def toplama(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def birlestirme(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_son_servisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'toplama': grpc.unary_unary_rpc_method_handler(
                    servicer.toplama,
                    request_deserializer=last__dance__pb2.istek_sayilar.FromString,
                    response_serializer=last__dance__pb2.cevap_toplam.SerializeToString,
            ),
            'birlestirme': grpc.unary_unary_rpc_method_handler(
                    servicer.birlestirme,
                    request_deserializer=last__dance__pb2.istek_isimler.FromString,
                    response_serializer=last__dance__pb2.cevap_isim.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.son_servis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greet.son_servis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class son_servis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def toplama(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.son_servis/toplama',
            last__dance__pb2.istek_sayilar.SerializeToString,
            last__dance__pb2.cevap_toplam.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def birlestirme(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.son_servis/birlestirme',
            last__dance__pb2.istek_isimler.SerializeToString,
            last__dance__pb2.cevap_isim.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
